services:
  db:
    container_name: postgres_db
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DJANGO_ENV: production
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net

  django-app-prod:
    container_name: django-backend-prod
    build:
      context: ./Ecommerce_app
      dockerfile: Dockerfile.prod
    command: gunicorn Ecommerce_app.wsgi:application --bind 0.0.0.0:8000 --workers=4
    volumes:
      - ./Ecommerce_app:/code
      - static_volume:/code/static
      - media_volume:/code/media
    depends_on:
      - db
    expose:
      - "7011:8000"
    networks:
      - app_net

  frontend-prod:
    container_name: Nextjs_frontend_prod
    build:
      context: ./frontend/my-app
      dockerfile: Dockerfile.prod
    ports:
      - "7010:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app_net

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  app_net:
